server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: yml-config
              uri: http://localhost:8080
              predicates:
                - Path=/gateway/api/yml/**
                - Method=GET
              filters:
                - name: YmlRouteFilter
                  args:
                    param: YML Config
                - RewritePath=/gateway(?<segment>.*), ${segment}
