### 1. 댓글 생성
POST {{api-url}}/api/replies
Content-Type: application/json

{
  "postId": 1,
  "userName": "admin",
  "password": "password",
  "title": "title",
  "contents": "contents"
}

### 2. 댓글 삭제
POST {{api-url}}/api/replies/delete
Authentication: TRUE
Content-Type: application/json

{
  "id": 1,
  "password": "password"
}
